const UI_TEXT = {
  pageTitle: "DnD Stronghold - Prototype",
  appTitle: "DnD Stronghold (Prototype)",
  hudToggleHide: "Hide",
  hudFabLabel: "Menu",
  defenseLabel: "Defenses",
  spellScrollLabel: "Spell Scrolls",
  factionsLabel: "Foes",
  hintDrag: "Drag a defense or spell scroll to deploy it.",
  hintDefenseSelect: "Select a defense to view details.",
  hintSpellScrollDrag: "Drag a spell scroll onto the path. Scrolls have limited uses.",
  upgradeTitle: "Training Grounds",
  upgradePrompt: "Level up this defense?",
  upgradeButton: "Level Up",
  siegeSetTargetLabel: "Set Target",
  siegeSetTargetAria: "Set siege target",
  siegeTargetLabel: (col?: number, row?: number) =>
    col !== undefined && row !== undefined ? `Target: (${col + 1}, ${row + 1})` : "Target: none",
  removeDefenseLabel: "Dismantle",
  removeDefenseAria: "Dismantle defense",
  upgradeMax: "Max level reached",
  upgradeCost: (cost: number) => `Cost: ${cost} gp`,
  upgradeLevel: (level: number, max: number) => `Level ${level}/${max}`,
  statDamage: "Damage",
  statRange: "Range",
  statRate: "Rate",
  statKnockback: "Knockback",
  statArrow: "->",
  defeatTitle: "Routed",
  defeatMessage: "Your stronghold has fallen. Try again?",
  defeatReset: "Restart Campaign",
  startWaveAria: "Begin encounter",
  startWaveLabel: "Begin Encounter",
  autoWaveOnAria: "Auto encounter on",
  autoWaveOffAria: "Auto encounter off",
  resetAria: "Restart campaign",
  resetConfirmTitle: "Restart Campaign?",
  resetConfirmMessage: "This will restart your run. Are you sure?",
  resetConfirmConfirm: "Restart",
  resetConfirmCancel: "Cancel",
  soundOnAria: "Sound on",
  soundOffAria: "Sound off",
  damagePopupsOnAria: "Damage popups on",
  damagePopupsOffAria: "Damage popups off",
  speedLabel: (label: string) => `Speed ${label}`,
  fullscreenEnterAria: "Enter fullscreen",
  fullscreenExitAria: "Exit fullscreen",
  stats: (gold: number, hp: number, wave: number) =>
    `Gold: ${gold} gp | HP: ${hp} | Encounter: ${wave}`,
  foeFaction: (name: string) => `Opposition: ${name}`,
  nextWave: (seconds: number) => `Next encounter (${seconds})`,
};

export { UI_TEXT };
