const UI_TEXT = {
  pageTitle: "Fantasy TD - Prototype",
  appTitle: "Fantasy TD (Prototype)",
  hudToggleHide: "Hide",
  hudFabLabel: "Menu",
  towerLabel: "Tower",
  factionsLabel: "Factions",
  hintDrag: "Drag a tile to place a tower.",
  hintTowerSelect: "Click a tower to view details.",
  upgradeTitle: "Tower Upgrade",
  upgradePrompt: "Level up this tower?",
  upgradeButton: "Upgrade",
  upgradeMax: "Max level reached",
  upgradeCost: (cost: number) => `Cost: ${cost}g`,
  upgradeLevel: (level: number, max: number) => `Level ${level}/${max}`,
  statDamage: "Damage",
  statRange: "Range",
  statRate: "Rate",
  statKnockback: "Knockback",
  statArrow: "->",
  defeatTitle: "Defeat",
  defeatMessage: "Your defenses fell. Want to try again?",
  defeatReset: "Reset Game",
  startWaveAria: "Start wave",
  startWaveLabel: "Start Wave",
  autoWaveOnAria: "Auto wave on",
  autoWaveOffAria: "Auto wave off",
  resetAria: "Reset game",
  resetConfirmTitle: "Reset Game?",
  resetConfirmMessage: "This will restart your run. Are you sure?",
  resetConfirmConfirm: "Reset",
  resetConfirmCancel: "Cancel",
  soundOnAria: "Sound on",
  soundOffAria: "Sound off",
  speedLabel: (label: string) => `Speed ${label}`,
  fullscreenEnterAria: "Enter fullscreen",
  fullscreenExitAria: "Exit fullscreen",
  stats: (gold: number, lives: number, wave: number) => `Gold: ${gold} | Lives: ${lives} | Wave: ${wave}`,
  enemyFaction: (name: string) => `Enemy Faction: ${name}`,
  nextWave: (seconds: number) => `Next wave (${seconds})`,
};

export { UI_TEXT };
