import type { FactionConfig } from "../../types/core/types";
import { TOWER_IDS } from "../../constants/towerIds";
import { TRAP_IDS } from "../../constants/trapIds";

const GRID_CONFIG = {
  cols: 16,
  rows: 9,
};

const GAMEPLAY_CONFIG = {
  startingGold: 140,
  startingLives: 15,
  maxLives: 15,
  startingWave: 1,
  speedSteps: [1, 1.5, 2],
  countdownSeconds: 5,
  killReward: 6,
  bossLifeLoss: 3,
  flawlessLifeGain: 1,
  bossFlawlessLifeGain: 3,
  enemyTurnStrength: 10,
  enemyArrivalThreshold: 0.2,
  knockbackSpeed: 8,
  backtrackThreshold: 0.02,
  projectileSpeed: 4.5,
  catapultProjectileSpeed: 3,
  catapultSplashRadiusTiles: 1,
  archerTreeDamageBonus: 0.12,
};

const WAVE_CONFIG = {
  initialSpawnDelay: 0.2,
  spawnInterval: 0.7,
  baseSpawns: 12,
  spawnsPerWave: 2,
  waveReward: 40,
};

const TOWER_CONFIG = {
  minRange: 1.3,
  maxLevel: 3,
  levelStats: [
    { damageMult: 1, rangeMult: 1, rateMult: 1, knockbackMult: 1 },
    { damageMult: 1.2, rangeMult: 1.1, rateMult: 0.92, knockbackMult: 1.1 },
    { damageMult: 1.4, rangeMult: 1.2, rateMult: 0.85, knockbackMult: 1.2 },
    { damageMult: 1.7, rangeMult: 1.3, rateMult: 0.78, knockbackMult: 1.3 },
  ],
  levelCosts: [
    { level: 1, costMultiplier: 1.2 },
    { level: 2, costMultiplier: 1.6 },
    { level: 3, costMultiplier: 2.1 },
  ],
  types: [
    {
      id: TOWER_IDS.mage,
      name: "Arcane Tower",
      types: ["Magic", "Ranged"],
      cost: 65,
      range: 1.8,
      rate: 1.0,
      damage: 11,
      damageType: "force",
      critChance: 0.04,
      critMultiplier: 1.6,
      knockback: 0,
      damageResistances: {},
      damageGroupResistances: {},
      color: "#7fd1b9",
      description: "Magic bolts, long range.",
    },
    {
      id: TOWER_IDS.archer,
      name: "Elven Archer",
      types: ["Bow", "Ranged"],
      cost: 60,
      range: 2.4,
      rate: 0.7,
      damage: 7,
      damageType: "piercing",
      critChance: 0.07,
      critMultiplier: 1.5,
      knockback: 0,
      damageResistances: {},
      damageGroupResistances: {},
      color: "#e7c27d",
      description: "Fast arrows.",
    },
    {
      id: TOWER_IDS.blade,
      name: "Sword Guard",
      types: ["Melee"],
      cost: 48,
      range: 1.3,
      rate: 0.6,
      damage: 10,
      damageType: "slashing",
      critChance: 0.05,
      critMultiplier: 1.6,
      knockback: 0,
      damageResistances: {},
      damageGroupResistances: {},
      color: "#d16f7a",
      description: "Short reach, hard hit.",
    },
    {
      id: TOWER_IDS.warden,
      name: "Aegis Warden",
      types: ["Shield", "Melee"],
      cost: 85,
      range: 1.3,
      rate: 1.0,
      damage: 2,
      damageType: "bludgeoning",
      critChance: 0.02,
      critMultiplier: 1.4,
      knockback: 0.4,
      damageResistances: {},
      damageGroupResistances: {},
      color: "#7aa6c9",
      description: "Shield bash, knocks foes back.",
    },
    {
      id: TOWER_IDS.catapult,
      name: "Catapult",
      types: ["Siege", "Ranged"],
      cost: 190,
      range: 6.5,
      rate: 7,
      damage: 55,
      damageType: "bludgeoning",
      critChance: 0.08,
      critMultiplier: 1.8,
      knockback: 0.15,
      damageResistances: {},
      damageGroupResistances: {},
      color: "#c58b5a",
      description: "Lobs massive shots at a fixed target.",
    },
  ],
};

const TRAP_CONFIG = {
  types: [
    {
      id: TRAP_IDS.tacks,
      name: "Tacks",
      types: ["Damage", "Trap"],
      cost: 45,
      maxTriggers: 10,
      cooldownSeconds: 6,
      damage: 7,
      damageType: "piercing",
      description: "Scatters sharp tacks that nick passersby.",
    },
    {
      id: TRAP_IDS.spike,
      name: "Spike Pit",
      types: ["Damage", "Trap"],
      cost: 80,
      maxTriggers: 4,
      cooldownSeconds: 10,
      damage: 18,
      damageType: "piercing",
      description: "Hidden spikes for heavy single-target hits.",
    },
    {
      id: TRAP_IDS.glue,
      name: "Glue Trap",
      types: ["Slow", "Trap"],
      cost: 70,
      maxTriggers: 10,
      cooldownSeconds: 12,
      slowMultiplier: 0.4,
      slowDuration: 5,
      description: "Sticky glue slows enemies that step on it.",
    },
    {
      id: TRAP_IDS.shock,
      name: "Shock Rune",
      types: ["Damage", "Slow", "Splash", "Trap"],
      cost: 90,
      maxTriggers: 1,
      cooldownSeconds: 18,
      damage: 15,
      damageType: "lightning",
      splashRadiusTiles: 0.8,
      slowMultiplier: 0.7,
      slowDuration: 1.6,
      description: "Shocks targets and briefly slows them.",
    },
    {
      id: TRAP_IDS.nuke,
      name: "Nuke",
      types: ["Splash", "Trap"],
      cost: 1000,
      maxTriggers: 1,
      cooldownPerWave: true,
      damage: 9999,
      damageType: "fire",
      killsAll: true,
      description: "Obliterates everything left in the wave.",
    },
    {
      id: TRAP_IDS.bomb,
      name: "Bomb Trap",
      types: ["Splash", "Trap"],
      cost: 120,
      maxTriggers: 1,
      cooldownSeconds: 25,
      damage: 45,
      damageType: "fire",
      splashRadiusTiles: 1.5,
      description: "Explodes for massive splash damage.",
    },
  ],
};

const ENEMY_CONFIG = {
  baseHp: 32,
  hpPerWave: 7,
  baseSpeed: 0.6,
  speedPerWave: 0.035,
  bossInterval: 10,
  bossHpMultiplier: 8,
  bossSpeedMultiplier: 0.4,
  bossScale: 1.6,
  bossKnockbackResistSeconds: 1.25,
  bossKnockbackDistanceMultiplier: 0.45,
  types: {
    skirmisher: {
      hpMultiplier: 0.6,
      speedMultiplier: 1.35,
      sizeScale: 0.75,
      knockbackResistSeconds: 0.12,
      knockbackDistanceMultiplier: 1.6,
      damageResistances: {},
      damageGroupResistances: {},
    },
    raider: {
      hpMultiplier: 1,
      speedMultiplier: 1,
      sizeScale: 1,
      knockbackResistSeconds: 0.22,
      knockbackDistanceMultiplier: 1,
      damageResistances: {},
      damageGroupResistances: {},
    },
    bruiser: {
      hpMultiplier: 1.6,
      speedMultiplier: 0.85,
      sizeScale: 1.1,
      knockbackResistSeconds: 0.35,
      knockbackDistanceMultiplier: 0.6,
      damageResistances: {},
      damageGroupResistances: {},
    },
    bulwark: {
      hpMultiplier: 2.4,
      speedMultiplier: 0.6,
      sizeScale: 1.25,
      knockbackResistSeconds: 0.7,
      knockbackDistanceMultiplier: 0.45,
      damageResistances: {},
      damageGroupResistances: {},
    },
    elite: {
      hpMultiplier: 1.8,
      speedMultiplier: 1.1,
      sizeScale: 1.05,
      knockbackResistSeconds: 0.8,
      knockbackDistanceMultiplier: 0.55,
      damageResistances: {},
      damageGroupResistances: {},
    },
  },
  typeSpawnWeights: [
    { maxWave: 2, weights: { raider: 0.6, skirmisher: 0.4 } },
    { maxWave: 4, weights: { raider: 0.55, skirmisher: 0.3, bruiser: 0.15 } },
    { maxWave: 6, weights: { raider: 0.45, skirmisher: 0.25, bruiser: 0.2, bulwark: 0.1 } },
    { maxWave: 8, weights: { raider: 0.4, skirmisher: 0.2, bruiser: 0.2, bulwark: 0.15, elite: 0.05 } },
    { maxWave: 9, weights: { raider: 0.35, skirmisher: 0.15, bruiser: 0.22, bulwark: 0.18, elite: 0.1 } },
    { maxWave: 10, weights: { raider: 0.3, skirmisher: 0.1, bruiser: 0.25, bulwark: 0.2, elite: 0.15 } },
  ],
  typeSpawnWeightsByFaction: {
    humans: [
      { maxWave: 2, weights: { raider: 0.65, skirmisher: 0.35 } },
      { maxWave: 4, weights: { raider: 0.6, skirmisher: 0.25, bruiser: 0.15 } },
      { maxWave: 6, weights: { raider: 0.5, skirmisher: 0.2, bruiser: 0.2, bulwark: 0.1 } },
      { maxWave: 8, weights: { raider: 0.45, skirmisher: 0.15, bruiser: 0.2, bulwark: 0.15, elite: 0.05 } },
      { maxWave: 9, weights: { raider: 0.4, skirmisher: 0.12, bruiser: 0.22, bulwark: 0.18, elite: 0.08 } },
      { maxWave: 10, weights: { raider: 0.35, skirmisher: 0.1, bruiser: 0.25, bulwark: 0.2, elite: 0.1 } },
    ],
    orcs: [
      { maxWave: 2, weights: { raider: 0.55, skirmisher: 0.45 } },
      { maxWave: 4, weights: { raider: 0.5, skirmisher: 0.3, bruiser: 0.2 } },
      { maxWave: 6, weights: { raider: 0.4, skirmisher: 0.2, bruiser: 0.25, bulwark: 0.15 } },
      { maxWave: 8, weights: { raider: 0.35, skirmisher: 0.15, bruiser: 0.25, bulwark: 0.2, elite: 0.05 } },
      { maxWave: 9, weights: { raider: 0.3, skirmisher: 0.12, bruiser: 0.28, bulwark: 0.22, elite: 0.08 } },
      { maxWave: 10, weights: { raider: 0.25, skirmisher: 0.1, bruiser: 0.3, bulwark: 0.22, elite: 0.13 } },
    ],
    elves: [
      { maxWave: 2, weights: { raider: 0.5, skirmisher: 0.5 } },
      { maxWave: 4, weights: { raider: 0.45, skirmisher: 0.35, bruiser: 0.2 } },
      { maxWave: 6, weights: { raider: 0.4, skirmisher: 0.3, bruiser: 0.2, bulwark: 0.1 } },
      { maxWave: 8, weights: { raider: 0.35, skirmisher: 0.25, bruiser: 0.2, bulwark: 0.12, elite: 0.08 } },
      { maxWave: 9, weights: { raider: 0.3, skirmisher: 0.22, bruiser: 0.2, bulwark: 0.13, elite: 0.15 } },
      { maxWave: 10, weights: { raider: 0.28, skirmisher: 0.2, bruiser: 0.2, bulwark: 0.12, elite: 0.2 } },
    ],
    undead: [
      { maxWave: 2, weights: { raider: 0.55, skirmisher: 0.45 } },
      { maxWave: 4, weights: { raider: 0.5, skirmisher: 0.3, bruiser: 0.2 } },
      { maxWave: 6, weights: { raider: 0.4, skirmisher: 0.2, bruiser: 0.25, bulwark: 0.15 } },
      { maxWave: 8, weights: { raider: 0.35, skirmisher: 0.15, bruiser: 0.25, bulwark: 0.2, elite: 0.05 } },
      { maxWave: 9, weights: { raider: 0.3, skirmisher: 0.1, bruiser: 0.28, bulwark: 0.22, elite: 0.1 } },
      { maxWave: 10, weights: { raider: 0.25, skirmisher: 0.08, bruiser: 0.3, bulwark: 0.25, elite: 0.12 } },
    ],
    dwarves: [
      { maxWave: 2, weights: { raider: 0.6, skirmisher: 0.4 } },
      { maxWave: 4, weights: { raider: 0.55, skirmisher: 0.25, bruiser: 0.2 } },
      { maxWave: 6, weights: { raider: 0.45, skirmisher: 0.18, bruiser: 0.25, bulwark: 0.12 } },
      { maxWave: 8, weights: { raider: 0.38, skirmisher: 0.15, bruiser: 0.25, bulwark: 0.17, elite: 0.05 } },
      { maxWave: 9, weights: { raider: 0.33, skirmisher: 0.12, bruiser: 0.27, bulwark: 0.2, elite: 0.08 } },
      { maxWave: 10, weights: { raider: 0.3, skirmisher: 0.1, bruiser: 0.28, bulwark: 0.22, elite: 0.1 } },
    ],
    spirits: [
      { maxWave: 2, weights: { raider: 0.45, skirmisher: 0.55 } },
      { maxWave: 4, weights: { raider: 0.4, skirmisher: 0.4, bruiser: 0.2 } },
      { maxWave: 6, weights: { raider: 0.35, skirmisher: 0.3, bruiser: 0.2, bulwark: 0.15 } },
      { maxWave: 8, weights: { raider: 0.3, skirmisher: 0.25, bruiser: 0.2, bulwark: 0.15, elite: 0.1 } },
      { maxWave: 9, weights: { raider: 0.28, skirmisher: 0.22, bruiser: 0.2, bulwark: 0.15, elite: 0.15 } },
      { maxWave: 10, weights: { raider: 0.25, skirmisher: 0.2, bruiser: 0.2, bulwark: 0.15, elite: 0.2 } },
    ],
    demons: [
      { maxWave: 2, weights: { raider: 0.5, skirmisher: 0.5 } },
      { maxWave: 4, weights: { raider: 0.45, skirmisher: 0.3, bruiser: 0.25 } },
      { maxWave: 6, weights: { raider: 0.35, skirmisher: 0.2, bruiser: 0.25, bulwark: 0.2 } },
      { maxWave: 8, weights: { raider: 0.3, skirmisher: 0.15, bruiser: 0.25, bulwark: 0.2, elite: 0.1 } },
      { maxWave: 9, weights: { raider: 0.27, skirmisher: 0.12, bruiser: 0.27, bulwark: 0.22, elite: 0.12 } },
      { maxWave: 10, weights: { raider: 0.24, skirmisher: 0.1, bruiser: 0.28, bulwark: 0.23, elite: 0.15 } },
    ],
    dragons: [
      { maxWave: 2, weights: { raider: 0.55, skirmisher: 0.45 } },
      { maxWave: 4, weights: { raider: 0.5, skirmisher: 0.25, bruiser: 0.25 } },
      { maxWave: 6, weights: { raider: 0.4, skirmisher: 0.2, bruiser: 0.25, bulwark: 0.15 } },
      { maxWave: 8, weights: { raider: 0.35, skirmisher: 0.15, bruiser: 0.25, bulwark: 0.15, elite: 0.1 } },
      { maxWave: 9, weights: { raider: 0.3, skirmisher: 0.12, bruiser: 0.27, bulwark: 0.18, elite: 0.13 } },
      { maxWave: 10, weights: { raider: 0.26, skirmisher: 0.1, bruiser: 0.28, bulwark: 0.2, elite: 0.16 } },
    ],
  },
};

const FACTION_PROGRESSION: FactionConfig[] = [
  { id: "humans", name: "Human Vanguard", start: 1, end: 10 },
  { id: "orcs", name: "Orc Marauders", start: 11, end: 20 },
  { id: "elves", name: "Elven Raiders", start: 21, end: 30 },
  { id: "undead", name: "Undead Legion", start: 31, end: 40 },
  { id: "dwarves", name: "Dwarven Reavers", start: 41, end: 50 },
  { id: "spirits", name: "Spirit Host", start: 51, end: 60 },
  { id: "demons", name: "Demonic Horde", start: 61, end: 70 },
  { id: "dragons", name: "Dragonkin", start: 71, end: 9999 },
];

const getFactionForWave = (waveNumber: number) =>
  FACTION_PROGRESSION.find((faction) => waveNumber >= faction.start && waveNumber <= faction.end) ??
  FACTION_PROGRESSION[FACTION_PROGRESSION.length - 1];

export {
  ENEMY_CONFIG,
  FACTION_PROGRESSION,
  GAMEPLAY_CONFIG,
  GRID_CONFIG,
  TRAP_CONFIG,
  TOWER_CONFIG,
  WAVE_CONFIG,
  getFactionForWave,
};
