import type { DefenseType, FactionConfig, SpellScrollType } from "../../types/core/types";
import type { DefenseLevelCostScale, DefenseLevelStats } from "../../types/core/configTypes";
import { DEFENSE_IDS } from "../../constants/defenseIds";
import { SPELL_SCROLL_IDS } from "../../constants/spellScrollIds";

const GRID_CONFIG = {
  cols: 16,
  rows: 9,
};

const GAMEPLAY_CONFIG = {
  startingGold: 140,
  startingHp: 15,
  maxHp: 15,
  startingWave: 1,
  speedSteps: [1, 1.5, 2],
  countdownSeconds: 5,
  killReward: 6,
  bossHpLoss: 3,
  flawlessHpGain: 1,
  bossFlawlessHpGain: 3,
  foeTurnStrength: 10,
  foeArrivalThreshold: 0.2,
  knockbackSpeed: 8,
  backtrackThreshold: 0.02,
  projectileSpeed: 4.5,
  siegeProjectileSpeed: 3,
  siegeSplashRadiusTiles: 1,
  rangerTreeDamageBonus: 0.12,
};

const WAVE_CONFIG = {
  initialSpawnDelay: 0.2,
  spawnInterval: 0.7,
  baseSpawns: 12,
  spawnsPerWave: 2,
  waveReward: 40,
};

const DEFENSE_CONFIG = {
  minRange: 1.3,
  maxLevel: 3,
  levelStats: [
    { damageMult: 1, rangeMult: 1, rateMult: 1, knockbackMult: 1 },
    { damageMult: 1.2, rangeMult: 1.1, rateMult: 0.92, knockbackMult: 1.1 },
    { damageMult: 1.4, rangeMult: 1.2, rateMult: 0.85, knockbackMult: 1.2 },
    { damageMult: 1.7, rangeMult: 1.3, rateMult: 0.78, knockbackMult: 1.3 },
  ],
  levelCosts: [
    { level: 1, costMultiplier: 1.2 },
    { level: 2, costMultiplier: 1.6 },
    { level: 3, costMultiplier: 2.1 },
  ],
  types: [
    {
      id: DEFENSE_IDS.barbarian,
      name: "Barbarian Warcamp",
      types: ["Martial", "Melee"],
      cost: 90,
      range: 1.35,
      rate: 1.2,
      damage: 18,
      damageType: "slashing",
      critChance: 0.03,
      critMultiplier: 1.5,
      knockback: 0,
      damageResistances: {},
      damageGroupResistances: {},
      color: "#c77a4a",
      description: "Frenzied strikes that batter the front line.",
    },
    {
      id: DEFENSE_IDS.bard,
      name: "Bard College",
      types: ["Arcane", "Ranged"],
      cost: 85,
      range: 2.1,
      rate: 0.75,
      damage: 0,
      damageType: "thunder",
      critChance: 0.06,
      critMultiplier: 1.4,
      knockback: 0,
      auraRangeTiles: 2.5,
      auraBonuses: {
        damageMult: 1.12,
        rangeMult: 1.1,
        rateMult: 0.9,
      },
      damageResistances: {},
      damageGroupResistances: {},
      color: "#b58ad6",
      description: "Inspiring melodies bolster nearby allies.",
    },
    {
      id: DEFENSE_IDS.cleric,
      name: "Cleric Chapel",
      types: ["Divine", "Ranged"],
      cost: 82,
      range: 2.1,
      rate: 1.0,
      damage: 9,
      damageType: "radiant",
      critChance: 0.04,
      critMultiplier: 1.5,
      knockback: 0,
      damageResistances: {},
      damageGroupResistances: {},
      color: "#e6d4a2",
      description: "Radiant bolts sear the unholy.",
    },
    {
      id: DEFENSE_IDS.druid,
      name: "Druid Grove",
      types: ["Primal", "Ranged"],
      cost: 80,
      range: 2.4,
      rate: 0.85,
      damage: 7,
      damageType: "poison",
      critChance: 0.04,
      critMultiplier: 1.4,
      knockback: 0,
      damageResistances: {},
      damageGroupResistances: {},
      color: "#79a96c",
      description: "Nature's wrath seeps into enemies.",
    },
    {
      id: DEFENSE_IDS.wizard,
      name: "Wizard's Tower",
      types: ["Arcane", "Ranged"],
      cost: 85,
      range: 2.1,
      rate: 1.0,
      damage: 12,
      damageType: "force",
      critChance: 0.05,
      critMultiplier: 1.6,
      knockback: 0,
      damageResistances: {},
      damageGroupResistances: {},
      color: "#7fd1b9",
      description: "Arcane bolts and precise spellfire.",
    },
    {
      id: DEFENSE_IDS.monk,
      name: "Monk Dojo",
      types: ["Martial", "Melee"],
      cost: 65,
      range: 1.3,
      rate: 0.4,
      damage: 4,
      damageType: "bludgeoning",
      critChance: 0.04,
      critMultiplier: 1.4,
      knockback: 0.18,
      damageResistances: {},
      damageGroupResistances: {},
      color: "#d2a85c",
      description: "Blindingly fast strikes at close range.",
    },
    {
      id: DEFENSE_IDS.ranger,
      name: "Ranger Outpost",
      types: ["Martial", "Ranged"],
      cost: 62,
      range: 2.6,
      rate: 0.7,
      damage: 7,
      damageType: "piercing",
      critChance: 0.07,
      critMultiplier: 1.5,
      knockback: 0,
      damageResistances: {},
      damageGroupResistances: {},
      color: "#e7c27d",
      description: "Rapid volleys from trained hunters.",
    },
    {
      id: DEFENSE_IDS.rogue,
      name: "Rogue Hideout",
      types: ["Martial", "Melee"],
      cost: 78,
      range: 1.45,
      rate: 0.65,
      damage: 8,
      damageType: "piercing",
      critChance: 0.14,
      critMultiplier: 1.9,
      knockback: 0,
      damageResistances: {},
      damageGroupResistances: {},
      color: "#7a6f86",
      description: "Precise strikes with deadly criticals.",
    },
    {
      id: DEFENSE_IDS.sorcerer,
      name: "Sorcerer Spire",
      types: ["Arcane", "Ranged"],
      cost: 110,
      range: 2.5,
      rate: 1.4,
      damage: 18,
      damageType: "fire",
      critChance: 0.04,
      critMultiplier: 1.7,
      knockback: 0,
      damageResistances: {},
      damageGroupResistances: {},
      color: "#e6765f",
      description: "Raw elemental bursts scorch foes.",
    },
    {
      id: DEFENSE_IDS.warlock,
      name: "Warlock Sanctum",
      types: ["Arcane", "Ranged"],
      cost: 95,
      range: 2.35,
      rate: 1.1,
      damage: 13,
      damageType: "necrotic",
      critChance: 0.05,
      critMultiplier: 1.7,
      knockback: 0,
      damageResistances: {},
      damageGroupResistances: {},
      color: "#7b5cc2",
      description: "Eldritch power with sinister reach.",
    },
    {
      id: DEFENSE_IDS.fighter,
      name: "Fighter Barracks",
      types: ["Martial", "Melee"],
      cost: 60,
      range: 1.3,
      rate: 0.6,
      damage: 9,
      damageType: "slashing",
      critChance: 0.04,
      critMultiplier: 1.6,
      knockback: 0,
      damageResistances: {},
      damageGroupResistances: {},
      color: "#d16f7a",
      description: "Steel discipline on the front line.",
    },
    {
      id: DEFENSE_IDS.paladin,
      name: "Paladin Bastion",
      types: ["Divine", "Melee"],
      cost: 105,
      range: 1.3,
      rate: 0.95,
      damage: 4,
      damageType: "bludgeoning",
      critChance: 0.02,
      critMultiplier: 1.4,
      knockback: 0.45,
      damageResistances: {},
      damageGroupResistances: {},
      color: "#7aa6c9",
      description: "Holy bulwark that staggers foes.",
    },
    {
      id: DEFENSE_IDS.siegeEngine,
      name: "Siege Engine",
      types: ["Siege", "Ranged"],
      cost: 220,
      range: 6.5,
      rate: 7.5,
      damage: 60,
      damageType: "bludgeoning",
      critChance: 0.07,
      critMultiplier: 1.8,
      knockback: 0.15,
      damageResistances: {},
      damageGroupResistances: {},
      color: "#c58b5a",
      description: "Hurls boulders at a fixed target.",
    },
  ],
} satisfies {
  minRange: number;
  maxLevel: number;
  levelStats: DefenseLevelStats[];
  levelCosts: DefenseLevelCostScale[];
  types: DefenseType[];
};

const SPELL_SCROLL_CONFIG = {
  types: [
    {
      id: SPELL_SCROLL_IDS.tacks,
      name: "Caltrops",
      types: ["Physical", "Trap"],
      cost: 45,
      maxTriggers: 10,
      cooldownSeconds: 6,
      damage: 7,
      damageType: "piercing",
      description: "Scatters spikes to harry marching foes.",
    },
    {
      id: SPELL_SCROLL_IDS.spike,
      name: "Pit Trap",
      types: ["Physical", "Trap"],
      cost: 80,
      maxTriggers: 4,
      cooldownSeconds: 10,
      damage: 18,
      damageType: "piercing",
      description: "Spring-loaded spikes punish the unwary.",
    },
    {
      id: SPELL_SCROLL_IDS.glue,
      name: "Web Rune",
      types: ["Arcane", "Trap"],
      cost: 70,
      maxTriggers: 10,
      cooldownSeconds: 12,
      slowMultiplier: 0.4,
      slowDuration: 5,
      description: "Arcane webbing ensnares passing foes.",
    },
    {
      id: SPELL_SCROLL_IDS.shock,
      name: "Shocking Glyph",
      types: ["Arcane", "Trap"],
      cost: 90,
      maxTriggers: 1,
      cooldownSeconds: 18,
      damage: 15,
      damageType: "lightning",
      splashRadiusTiles: 0.8,
      slowMultiplier: 0.7,
      slowDuration: 1.6,
      description: "Lightning glyphs jolt and stagger foes.",
    },
    {
      id: SPELL_SCROLL_IDS.nuke,
      name: "Meteor Swarm Sigil",
      types: ["Arcane", "Trap"],
      cost: 1000,
      maxTriggers: 1,
      cooldownPerWave: true,
      damage: 9999,
      damageType: "fire",
      knockbackDistanceTiles: 2.2,
      killsAll: true,
      description: "Calls down cataclysmic fire from the skies.",
    },
    {
      id: SPELL_SCROLL_IDS.bomb,
      name: "Fireball Sigil",
      types: ["Arcane", "Trap"],
      cost: 120,
      maxTriggers: 1,
      cooldownSeconds: 25,
      damage: 45,
      damageType: "fire",
      knockbackDistanceTiles: 1.2,
      splashRadiusTiles: 1.5,
      description: "A rune that erupts in fiery blast.",
    },
  ],
} satisfies {
  types: SpellScrollType[];
};

const FOE_CONFIG = {
  baseHp: 32,
  hpPerWave: 7,
  baseSpeed: 0.6,
  speedPerWave: 0.035,
  bossInterval: 10,
  bossHpMultiplier: 8,
  bossSpeedMultiplier: 0.4,
  bossScale: 1.6,
  bossKnockbackResistSeconds: 1.25,
  bossKnockbackDistanceMultiplier: 0.45,
  types: {
    skirmisher: {
      hpMultiplier: 0.6,
      speedMultiplier: 1.35,
      sizeScale: 0.75,
      knockbackResistSeconds: 0.12,
      knockbackDistanceMultiplier: 1.6,
      damageResistances: {},
      damageGroupResistances: {},
    },
    raider: {
      hpMultiplier: 1,
      speedMultiplier: 1,
      sizeScale: 1,
      knockbackResistSeconds: 0.22,
      knockbackDistanceMultiplier: 1,
      damageResistances: {},
      damageGroupResistances: {},
    },
    bruiser: {
      hpMultiplier: 1.6,
      speedMultiplier: 0.85,
      sizeScale: 1.1,
      knockbackResistSeconds: 0.35,
      knockbackDistanceMultiplier: 0.6,
      damageResistances: {},
      damageGroupResistances: {},
    },
    bulwark: {
      hpMultiplier: 2.4,
      speedMultiplier: 0.6,
      sizeScale: 1.25,
      knockbackResistSeconds: 0.7,
      knockbackDistanceMultiplier: 0.45,
      damageResistances: {},
      damageGroupResistances: {},
    },
    elite: {
      hpMultiplier: 1.8,
      speedMultiplier: 1.1,
      sizeScale: 1.05,
      knockbackResistSeconds: 0.8,
      knockbackDistanceMultiplier: 0.55,
      damageResistances: {},
      damageGroupResistances: {},
    },
  },
  typeSpawnWeights: [
    { maxWave: 2, weights: { raider: 0.6, skirmisher: 0.4 } },
    { maxWave: 4, weights: { raider: 0.55, skirmisher: 0.3, bruiser: 0.15 } },
    { maxWave: 6, weights: { raider: 0.45, skirmisher: 0.25, bruiser: 0.2, bulwark: 0.1 } },
    { maxWave: 8, weights: { raider: 0.4, skirmisher: 0.2, bruiser: 0.2, bulwark: 0.15, elite: 0.05 } },
    { maxWave: 9, weights: { raider: 0.35, skirmisher: 0.15, bruiser: 0.22, bulwark: 0.18, elite: 0.1 } },
    { maxWave: 10, weights: { raider: 0.3, skirmisher: 0.1, bruiser: 0.25, bulwark: 0.2, elite: 0.15 } },
  ],
  typeSpawnWeightsByFaction: {
    humans: [
      { maxWave: 2, weights: { raider: 0.65, skirmisher: 0.35 } },
      { maxWave: 4, weights: { raider: 0.6, skirmisher: 0.25, bruiser: 0.15 } },
      { maxWave: 6, weights: { raider: 0.5, skirmisher: 0.2, bruiser: 0.2, bulwark: 0.1 } },
      { maxWave: 8, weights: { raider: 0.45, skirmisher: 0.15, bruiser: 0.2, bulwark: 0.15, elite: 0.05 } },
      { maxWave: 9, weights: { raider: 0.4, skirmisher: 0.12, bruiser: 0.22, bulwark: 0.18, elite: 0.08 } },
      { maxWave: 10, weights: { raider: 0.35, skirmisher: 0.1, bruiser: 0.25, bulwark: 0.2, elite: 0.1 } },
    ],
    orcs: [
      { maxWave: 2, weights: { raider: 0.55, skirmisher: 0.45 } },
      { maxWave: 4, weights: { raider: 0.5, skirmisher: 0.3, bruiser: 0.2 } },
      { maxWave: 6, weights: { raider: 0.4, skirmisher: 0.2, bruiser: 0.25, bulwark: 0.15 } },
      { maxWave: 8, weights: { raider: 0.35, skirmisher: 0.15, bruiser: 0.25, bulwark: 0.2, elite: 0.05 } },
      { maxWave: 9, weights: { raider: 0.3, skirmisher: 0.12, bruiser: 0.28, bulwark: 0.22, elite: 0.08 } },
      { maxWave: 10, weights: { raider: 0.25, skirmisher: 0.1, bruiser: 0.3, bulwark: 0.22, elite: 0.13 } },
    ],
    elves: [
      { maxWave: 2, weights: { raider: 0.5, skirmisher: 0.5 } },
      { maxWave: 4, weights: { raider: 0.45, skirmisher: 0.35, bruiser: 0.2 } },
      { maxWave: 6, weights: { raider: 0.4, skirmisher: 0.3, bruiser: 0.2, bulwark: 0.1 } },
      { maxWave: 8, weights: { raider: 0.35, skirmisher: 0.25, bruiser: 0.2, bulwark: 0.12, elite: 0.08 } },
      { maxWave: 9, weights: { raider: 0.3, skirmisher: 0.22, bruiser: 0.2, bulwark: 0.13, elite: 0.15 } },
      { maxWave: 10, weights: { raider: 0.28, skirmisher: 0.2, bruiser: 0.2, bulwark: 0.12, elite: 0.2 } },
    ],
    undead: [
      { maxWave: 2, weights: { raider: 0.55, skirmisher: 0.45 } },
      { maxWave: 4, weights: { raider: 0.5, skirmisher: 0.3, bruiser: 0.2 } },
      { maxWave: 6, weights: { raider: 0.4, skirmisher: 0.2, bruiser: 0.25, bulwark: 0.15 } },
      { maxWave: 8, weights: { raider: 0.35, skirmisher: 0.15, bruiser: 0.25, bulwark: 0.2, elite: 0.05 } },
      { maxWave: 9, weights: { raider: 0.3, skirmisher: 0.1, bruiser: 0.28, bulwark: 0.22, elite: 0.1 } },
      { maxWave: 10, weights: { raider: 0.25, skirmisher: 0.08, bruiser: 0.3, bulwark: 0.25, elite: 0.12 } },
    ],
    dwarves: [
      { maxWave: 2, weights: { raider: 0.6, skirmisher: 0.4 } },
      { maxWave: 4, weights: { raider: 0.55, skirmisher: 0.25, bruiser: 0.2 } },
      { maxWave: 6, weights: { raider: 0.45, skirmisher: 0.18, bruiser: 0.25, bulwark: 0.12 } },
      { maxWave: 8, weights: { raider: 0.38, skirmisher: 0.15, bruiser: 0.25, bulwark: 0.17, elite: 0.05 } },
      { maxWave: 9, weights: { raider: 0.33, skirmisher: 0.12, bruiser: 0.27, bulwark: 0.2, elite: 0.08 } },
      { maxWave: 10, weights: { raider: 0.3, skirmisher: 0.1, bruiser: 0.28, bulwark: 0.22, elite: 0.1 } },
    ],
    spirits: [
      { maxWave: 2, weights: { raider: 0.45, skirmisher: 0.55 } },
      { maxWave: 4, weights: { raider: 0.4, skirmisher: 0.4, bruiser: 0.2 } },
      { maxWave: 6, weights: { raider: 0.35, skirmisher: 0.3, bruiser: 0.2, bulwark: 0.15 } },
      { maxWave: 8, weights: { raider: 0.3, skirmisher: 0.25, bruiser: 0.2, bulwark: 0.15, elite: 0.1 } },
      { maxWave: 9, weights: { raider: 0.28, skirmisher: 0.22, bruiser: 0.2, bulwark: 0.15, elite: 0.15 } },
      { maxWave: 10, weights: { raider: 0.25, skirmisher: 0.2, bruiser: 0.2, bulwark: 0.15, elite: 0.2 } },
    ],
    demons: [
      { maxWave: 2, weights: { raider: 0.5, skirmisher: 0.5 } },
      { maxWave: 4, weights: { raider: 0.45, skirmisher: 0.3, bruiser: 0.25 } },
      { maxWave: 6, weights: { raider: 0.35, skirmisher: 0.2, bruiser: 0.25, bulwark: 0.2 } },
      { maxWave: 8, weights: { raider: 0.3, skirmisher: 0.15, bruiser: 0.25, bulwark: 0.2, elite: 0.1 } },
      { maxWave: 9, weights: { raider: 0.27, skirmisher: 0.12, bruiser: 0.27, bulwark: 0.22, elite: 0.12 } },
      { maxWave: 10, weights: { raider: 0.24, skirmisher: 0.1, bruiser: 0.28, bulwark: 0.23, elite: 0.15 } },
    ],
    dragons: [
      { maxWave: 2, weights: { raider: 0.55, skirmisher: 0.45 } },
      { maxWave: 4, weights: { raider: 0.5, skirmisher: 0.25, bruiser: 0.25 } },
      { maxWave: 6, weights: { raider: 0.4, skirmisher: 0.2, bruiser: 0.25, bulwark: 0.15 } },
      { maxWave: 8, weights: { raider: 0.35, skirmisher: 0.15, bruiser: 0.25, bulwark: 0.15, elite: 0.1 } },
      { maxWave: 9, weights: { raider: 0.3, skirmisher: 0.12, bruiser: 0.27, bulwark: 0.18, elite: 0.13 } },
      { maxWave: 10, weights: { raider: 0.26, skirmisher: 0.1, bruiser: 0.28, bulwark: 0.2, elite: 0.16 } },
    ],
  },
};

const FACTION_PROGRESSION: FactionConfig[] = [
  { id: "humans", name: "Bandit Companies", start: 1, end: 10 },
  { id: "orcs", name: "Orc Warbands", start: 11, end: 20 },
  { id: "elves", name: "Fey Court", start: 21, end: 30 },
  { id: "undead", name: "Necrotic Host", start: 31, end: 40 },
  { id: "dwarves", name: "Duergar Clans", start: 41, end: 50 },
  { id: "spirits", name: "Ethereal Covenant", start: 51, end: 60 },
  { id: "demons", name: "Abyssal Legion", start: 61, end: 70 },
  { id: "dragons", name: "Wyrmflight", start: 71, end: 9999 },
];

  const getFactionForWave = (waveNumber: number) =>
  FACTION_PROGRESSION.find((faction) => waveNumber >= faction.start && waveNumber <= faction.end) ??
  FACTION_PROGRESSION[FACTION_PROGRESSION.length - 1];

export {
  DEFENSE_CONFIG,
  FACTION_PROGRESSION,
  FOE_CONFIG,
  GAMEPLAY_CONFIG,
  GRID_CONFIG,
  SPELL_SCROLL_CONFIG,
  WAVE_CONFIG,
  getFactionForWave,
};
