import { DEFENSE_IDS } from "../constants/defenseIds";
import { SPELL_SCROLL_IDS } from "../constants/spellScrollIds";
import type { FoeType, FactionId, PixelSprite } from "../types/core/types";
import { GAME_CONFIG } from "./config";

const { grid, defenseTypes, spellScrollTypes } = GAME_CONFIG;
const MIN_DEFENSE_RANGE = GAME_CONFIG.defense.minRange;

const assertDefenseRanges = () => {
  const invalidDefenses = defenseTypes.filter((defense) => defense.range < MIN_DEFENSE_RANGE);
  if (invalidDefenses.length > 0) {
    const names = invalidDefenses.map((defense) => defense.name).join(", ");
    throw new Error(`Defense range below minimum (${MIN_DEFENSE_RANGE}): ${names}`);
  }
};

const pathPoints = [
  { x: 0, y: 4 },
  { x: 4, y: 4 },
  { x: 4, y: 2 },
  { x: 9, y: 2 },
  { x: 9, y: 6 },
  { x: 14, y: 6 },
  { x: 15, y: 7 },
];

const ENEMY_ARCHETYPE_PIXELS: Record<FoeType, string[]> = {
  skirmisher: [
    "........",
    "..aa....",
    ".a.a....",
    ".aac....",
    ".aa.....",
    "..a.....",
    ".a.a....",
    "..a.....",
  ],
  raider: [
    "..bbb...",
    ".babbb..",
    "babbab..",
    "bbacbb..",
    ".babb...",
    "..bbb...",
    ".b..b...",
    "b....b..",
  ],
  bruiser: [
    "..bbbb..",
    ".bbbbbb.",
    "bbbabbbb",
    "bbbacbbb",
    "bbbbbbbb",
    ".bbbbbb.",
    "..bbbb..",
    ".bb..bb.",
  ],
  bulwark: [
    "..bbbb..",
    ".bbbbbb.",
    "bbbbbbbb",
    "bbbcbbbb",
    "bbbbbbbb",
    ".bbbbbb.",
    ".bbbbbb.",
    "..b..b..",
  ],
  elite: [
    "..c..c..",
    ".bbbbbb.",
    "bbbabbbb",
    "bbbcbbbb",
    ".bbbbbb.",
    "..bbbb..",
    ".b..b...",
    "b....b..",
  ],
  boss: [
    ".dd..dd.",
    "dbbbbbd.",
    "bbbbbbbb",
    "bbbcbbbd",
    "bbbbbbbb",
    "dbbbbbd.",
    ".d.bb.d.",
    "..d..d..",
  ],
};

const ENEMY_FACTION_PALETTES: Record<FactionId, Record<string, string>> = {
  humans: { a: "#7b5e4a", b: "#c2b6a6", c: "#b8443a", d: "#e8d4a2" },
  orcs: { a: "#2f3a2a", b: "#5f8c44", c: "#c14a3f", d: "#7a4b2f" },
  elves: { a: "#cfe7d6", b: "#5ea884", c: "#cfa94a", d: "#f4efe6" },
  undead: { a: "#2f3436", b: "#7a8a8c", c: "#9fd0d4", d: "#c7c0b5" },
  dwarves: { a: "#4f3c32", b: "#b07a4a", c: "#f0dfc2", d: "#8b6b3f" },
  spirits: { a: "#e7f4ff", b: "#8bc8ff", c: "#6aa6d6", d: "#f8f4ff" },
  demons: { a: "#3d1616", b: "#b12c2c", c: "#f2b0a0", d: "#f2b36d" },
  dragons: { a: "#3f2a1b", b: "#7e5c3a", c: "#f2d5a0", d: "#8b6b3f" },
};

const buildEnemySprite = (pixels: string[], palette: Record<string, string>): PixelSprite => ({
  pixels,
  colors: palette,
});

const foeSprites: Record<FactionId, Record<FoeType, PixelSprite>> = Object.fromEntries(
  Object.entries(ENEMY_FACTION_PALETTES).map(([faction, palette]) => [
    faction,
    Object.fromEntries(
      Object.entries(ENEMY_ARCHETYPE_PIXELS).map(([type, pixels]) => [type, buildEnemySprite(pixels, palette)]),
    ),
  ]),
) as Record<FactionId, Record<FoeType, PixelSprite>>;

const defenseSprites: Record<string, PixelSprite> = {
  [DEFENSE_IDS.barbarian]: {
    pixels: [
      "....xx......",
      "...xRRx.....",
      "..xRRRRx....",
      ".xRRrRRRx...",
      ".xRRRRRRx...",
      "..xRRRRx....",
      "..xWWwwWx...",
      ".xWWWWWwx...",
      ".xWWwwWwx...",
      "xWWWWWWWWs.",
      "xWWWwWWxxs.",
      ".xWWWWWxxs.",
    ],
    colors: {
      x: "#1a1a1a",
      R: "#7a2f2f",
      r: "#b24b2f",
      W: "#c7c0b5",
      w: "#9f968a",
      s: "#6d4b2c",
    },
  },
  [DEFENSE_IDS.bard]: {
    pixels: [
      "....xx......",
      "...xxxx.....",
      "..xHhhHx....",
      ".xHHhHHHx...",
      ".xHHHHHHx...",
      "..xHHHHx....",
      "..xBBeeBx...",
      ".xBBBBBbx.s.",
      ".xBBBBbbx.s.",
      "xBBBBBBBBx.s",
      "xBBBBbBBxxS.",
      ".xBBBBBBxxS.",
    ],
    colors: {
      x: "#1a1a1a",
      H: "#7b3f8e",
      h: "#a161c2",
      B: "#3a4f8c",
      b: "#2b3a66",
      e: "#f2d47a",
      s: "#b08555",
      S: "#6b4a2c",
    },
  },
  [DEFENSE_IDS.cleric]: {
    pixels: [
      "....xx......",
      "...xxxx.....",
      "..xHhhHx....",
      ".xHHhHHHx...",
      ".xHHHHHHx...",
      "..xHHHHx....",
      "..xBBeeBx...",
      ".xBBBBBbx.s.",
      ".xBBBBbbx.s.",
      "xBBBBBBBBx.s",
      "xBBBBbBBxxS.",
      ".xBBBBBBxxS.",
    ],
    colors: {
      x: "#1a1a1a",
      H: "#c7a24b",
      h: "#e6c36f",
      B: "#d8d0bb",
      b: "#b9ad93",
      e: "#f2e8c6",
      s: "#a07a3e",
      S: "#6b4a2c",
    },
  },
  [DEFENSE_IDS.druid]: {
    pixels: [
      "....xx......",
      "...xxxx.....",
      "..xHhhHx....",
      ".xHHhHHHx...",
      ".xHHHHHHx...",
      "..xHHHHx....",
      "..xBBeeBx...",
      ".xBBBBBbx.s.",
      ".xBBBBbbx.s.",
      "xBBBBBBBBx.s",
      "xBBBBbBBxxS.",
      ".xBBBBBBxxS.",
    ],
    colors: {
      x: "#1a1a1a",
      H: "#3e6b3f",
      h: "#5a8c55",
      B: "#2c4a32",
      b: "#223a27",
      e: "#c4b874",
      s: "#7a5a33",
      S: "#5a4326",
    },
  },
  [DEFENSE_IDS.wizard]: {
    pixels: [
      "....xx......",
      "...xxxx.....",
      "..xHhhHx....",
      ".xHHhHHHx...",
      ".xHHHHHHx...",
      "..xHHHHx....",
      "..xBBeeBx...",
      ".xBBBBBbx.s.",
      ".xBBBBbbx.s.",
      "xBBBBBBBBx.s",
      "xBBBBbBBxxS.",
      ".xBBBBBBxxS.",
    ],
    colors: {
      x: "#1a1a1a",
      H: "#4c2a6b",
      h: "#6a3f8e",
      B: "#2f5f9e",
      b: "#1d3a66",
      e: "#f2d47a",
      s: "#b08555",
      S: "#6b4a2c",
    },
  },
  [DEFENSE_IDS.ranger]: {
    pixels: [
      "....xx......",
      "...xGGx.....",
      "..xGGGGx....",
      ".xGGgGGGx...",
      ".xGgGgGGx...",
      "..xGGGGx....",
      "..xEEeeEx...",
      ".xEEEEEex...",
      ".xEEeeEex...",
      "xEEEEEEEEs.",
      "xEEEeEExxs.",
      ".xEEEEExxs.",
    ],
    colors: {
      x: "#1a1a1a",
      G: "#2f6b4b",
      g: "#3f8f61",
      E: "#d9b574",
      e: "#b48947",
      s: "#7a5732",
    },
  },
  [DEFENSE_IDS.fighter]: {
    pixels: [
      "....xx......",
      "...xRRx.....",
      "..xRRRRx....",
      ".xRRrRRRx...",
      ".xRRRRRRx...",
      "..xRRRRx....",
      "..xWWwwWx...",
      ".xWWWWWwx...",
      ".xWWwwWwx...",
      "xWWWWWWWWs.",
      "xWWWwWWxxs.",
      ".xWWWWWxxs.",
    ],
    colors: {
      x: "#1a1a1a",
      R: "#566072",
      r: "#78839a",
      W: "#c7c0b5",
      w: "#9f968a",
      s: "#6d4b2c",
    },
  },
  [DEFENSE_IDS.paladin]: {
    pixels: [
      "....xx......",
      "...xSSx.....",
      "..xSSSSx....",
      ".xSSsSSSx...",
      ".xSSSSSSx...",
      "..xSSSSx....",
      "..xUUuuUx...",
      ".xUUUUUux...",
      ".xUUuuUux...",
      "xUUUUUQQQt.",
      "xUUuUQQxxt.",
      ".xUUUQQxxt.",
    ],
    colors: {
      x: "#1a1a1a",
      S: "#b08a3b",
      s: "#d2a85c",
      U: "#f0e7cf",
      u: "#c8b792",
      Q: "#a07a3e",
      t: "#6b4a2c",
    },
  },
  [DEFENSE_IDS.monk]: {
    pixels: [
      "....xx......",
      "...xRRx.....",
      "..xRRRRx....",
      ".xRRrRRRx...",
      ".xRRRRRRx...",
      "..xRRRRx....",
      "..xWWwwWx...",
      ".xWWWWWwx...",
      ".xWWwwWwx...",
      "xWWWWWWWWs.",
      "xWWWwWWxxs.",
      ".xWWWWWxxs.",
    ],
    colors: {
      x: "#1a1a1a",
      R: "#b9893a",
      r: "#d7b26a",
      W: "#c7c0b5",
      w: "#9f968a",
      s: "#6d4b2c",
    },
  },
  [DEFENSE_IDS.rogue]: {
    pixels: [
      "....xx......",
      "...xRRx.....",
      "..xRRRRx....",
      ".xRRrRRRx...",
      ".xRRRRRRx...",
      "..xRRRRx....",
      "..xWWwwWx...",
      ".xWWWWWwx...",
      ".xWWwwWwx...",
      "xWWWWWWWWs.",
      "xWWWwWWxxs.",
      ".xWWWWWxxs.",
    ],
    colors: {
      x: "#1a1a1a",
      R: "#4f5564",
      r: "#6a7386",
      W: "#c7c0b5",
      w: "#9f968a",
      s: "#5a4326",
    },
  },
  [DEFENSE_IDS.sorcerer]: {
    pixels: [
      "....xx......",
      "...xxxx.....",
      "..xHhhHx....",
      ".xHHhHHHx...",
      ".xHHHHHHx...",
      "..xHHHHx....",
      "..xBBeeBx...",
      ".xBBBBBbx.s.",
      ".xBBBBbbx.s.",
      "xBBBBBBBBx.s",
      "xBBBBbBBxxS.",
      ".xBBBBBBxxS.",
    ],
    colors: {
      x: "#1a1a1a",
      H: "#8a2f2f",
      h: "#d05a3a",
      B: "#4a2a2a",
      b: "#3a1f1f",
      e: "#f2d47a",
      s: "#b08555",
      S: "#6b4a2c",
    },
  },
  [DEFENSE_IDS.warlock]: {
    pixels: [
      "....xx......",
      "...xxxx.....",
      "..xHhhHx....",
      ".xHHhHHHx...",
      ".xHHHHHHx...",
      "..xHHHHx....",
      "..xBBeeBx...",
      ".xBBBBBbx.s.",
      ".xBBBBbbx.s.",
      "xBBBBBBBBx.s",
      "xBBBBbBBxxS.",
      ".xBBBBBBxxS.",
    ],
    colors: {
      x: "#1a1a1a",
      H: "#4b2f6b",
      h: "#6b4fa3",
      B: "#2a1f3f",
      b: "#1f1630",
      e: "#b5a6d6",
      s: "#8b6b3f",
      S: "#5a4326",
    },
  },
  [DEFENSE_IDS.siegeEngine]: {
    pixels: [
      "....xx......",
      "...xTTx.....",
      "..xTTTTx....",
      ".xTttTTTx...",
      ".xTTTTTTx...",
      "..xTTTTx....",
      "..xCCccCx...",
      ".xCCCCCCx...",
      ".xCCccCCx...",
      "xCCCCCCCCx..",
      "xCCcCCxCCx..",
      ".xCCCCCCx...",
    ],
    colors: {
      x: "#1a1a1a",
      T: "#5f4326",
      t: "#83603a",
      C: "#b07a4a",
      c: "#7a5632",
    },
  },
};

const spellScrollSprites: Record<string, PixelSprite> = {
  [SPELL_SCROLL_IDS.tacks]: {
    pixels: [
      "........",
      "..x..x..",
      ".x.x.x..",
      "..xxx...",
      ".x.x.x..",
      "..x..x..",
      "........",
      "........",
      "........",
    ],
    colors: {
      x: "#2b221b",
    },
  },
  [SPELL_SCROLL_IDS.spike]: {
    pixels: [
      "........",
      "..xxx...",
      ".xooo...",
      ".xooo...",
      ".xooo...",
      "..xxx...",
      "........",
      "........",
    ],
    colors: {
      x: "#a2855f",
      o: "#2a2420",
    },
  },
  [SPELL_SCROLL_IDS.glue]: {
    pixels: [
      "........",
      "..w.w...",
      ".w.www..",
      "..www...",
      "..www...",
      ".w.www..",
      "..w.w...",
      "........",
      "........",
      "........",
    ],
    colors: {
      w: "#c9c2a8",
    },
  },
  [SPELL_SCROLL_IDS.shock]: {
    pixels: [
      "....y...",
      "...yy...",
      "..y.y...",
      ".y..y...",
      "..y.y...",
      "...yy...",
      "...y....",
      "........",
    ],
    colors: {
      y: "#f2d47a",
    },
  },
  [SPELL_SCROLL_IDS.bomb]: {
    pixels: [
      "................................",
      "................................",
      ".............YYYY...............",
      "............YYYYYY..............",
      ".............YYYY...............",
      "..............YY................",
      "..............BB................",
      "..........BBBBBBBBBB............",
      ".......BBBBBDDDDDDBBBBB.........",
      ".....BBBBBDDDGGGGDDDDBBBBB.......",
      "....BBBBBDDGGGGGGGGDDDBBBB.......",
      "...BBBBBDDGGGGGGGGGGDDDBBBB......",
      "..BBBBBDDGGGGWWWWGGGGDDDBBBB.....",
      "..BBBBBDDGGGGWGGGWGGGGDDBBBB.....",
      "..BBBBBDDGGGGGGGGGGGGDDBBBB......",
      "..BBBBBDDGGGGGGGGGGGGDDBBBB......",
      "...BBBBBDDGGGGGGGGGGDDDBBBB......",
      "....BBBBBDDGGGGGGGGDDDBBBB.......",
      ".....BBBBBDDDGGGGDDDDBBBBB.......",
      ".......BBBBBDDDDDDBBBBB..........",
      "..........BBBBBBBBBB............",
      "..............BB................",
      "..............BB................",
      "..............BB................",
      "..............BB................",
      "..............BB................",
      "..............O.................",
      ".............OOO................",
      "..............O.................",
      "................................",
      "................................",
      "................................",
    ],
    colors: {
      f: "#d3643a",
      o: "#f2d47a",
    },
  },
  [SPELL_SCROLL_IDS.nuke]: {
    pixels: [
      "...m....",
      "..mmm...",
      ".mmomm..",
      ".mmoom..",
      ".mmomm..",
      "..mmm...",
      "...m....",
      "........",
    ],
    colors: {
      m: "#4a3a2a",
      o: "#d88f3a",
    },
  },
};

export {
  MIN_DEFENSE_RANGE,
  assertDefenseRanges,
  foeSprites,
  grid,
  pathPoints,
  spellScrollSprites,
  spellScrollTypes,
  defenseSprites,
  defenseTypes,
};
